#Requires -Version 5.1
# Zeude Uninstallation Script for Windows
$ErrorActionPreference = "Stop"

$ZeudeDir = Join-Path $env:USERPROFILE ".zeude"
$ClaudeDir = Join-Path $env:USERPROFILE ".claude"

Write-Host "Zeude Uninstaller" -ForegroundColor Red
Write-Host "======================================"
Write-Host ""
Write-Host "This will remove:" -ForegroundColor Yellow
Write-Host "  - Zeude shim and config (~\.zeude\)"
Write-Host "  - Zeude-installed hooks (~\.claude\hooks\)"
Write-Host "  - /zeude skill (~\.claude\commands\zeude.md)"
Write-Host "  - PATH configuration"
Write-Host ""

$Confirm = Read-Host "Are you sure you want to uninstall Zeude? (y/N)"
if ($Confirm -ne "y" -and $Confirm -ne "Y") {
    Write-Host "Uninstall cancelled."
    exit 0
}

Write-Host ""

# 1. Remove Zeude hooks
Write-Host -NoNewline "Removing Zeude hooks... "
$HooksRemoved = 0
$ManagedHooksFile = Join-Path $ZeudeDir "managed-hooks.json"
if (Test-Path $ManagedHooksFile) {
    try {
        $ManagedHooks = (Get-Content $ManagedHooksFile -Raw | ConvertFrom-Json).hooks
        foreach ($hook in $ManagedHooks) {
            if (Test-Path $hook) {
                Remove-Item $hook -Force
                $HooksRemoved++
            }
        }
    } catch { }
}

# Fallback: remove hooks with Zeude marker
$HooksDir = Join-Path $ClaudeDir "hooks"
if (Test-Path $HooksDir) {
    Get-ChildItem $HooksDir -Recurse -File | ForEach-Object {
        if ((Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue) -match "Auto-generated by Zeude") {
            Remove-Item $_.FullName -Force
            $script:HooksRemoved++
        }
    }
}

if ($HooksRemoved -gt 0) {
    Write-Host "Removed $HooksRemoved hooks" -ForegroundColor Green
} else {
    Write-Host "No hooks found" -ForegroundColor Yellow
}

# 2. Clean settings.json
Write-Host -NoNewline "Cleaning settings.json... "
$SettingsFile = Join-Path $ClaudeDir "settings.json"
if (Test-Path $SettingsFile) {
    try {
        $Settings = Get-Content $SettingsFile -Raw | ConvertFrom-Json
        if ($Settings.hooks) {
            $CleanHooks = [ordered]@{}
            foreach ($prop in $Settings.hooks.PSObject.Properties) {
                $Filtered = @($prop.Value | Where-Object {
                    $dominated = $false
                    if ($_.hooks) {
                        foreach ($h in $_.hooks) {
                            if ($h.command -like "*\.claude\hooks\*") { $dominated = $true }
                        }
                    }
                    -not $dominated
                })
                if ($Filtered.Count -gt 0) { $CleanHooks[$prop.Name] = $Filtered }
            }
            $Settings.hooks = $CleanHooks
        }
        $Settings | ConvertTo-Json -Depth 10 | Set-Content $SettingsFile
        Write-Host "OK" -ForegroundColor Green
    } catch {
        Write-Host "Failed: $_" -ForegroundColor Yellow
    }
} else {
    Write-Host "Not found" -ForegroundColor Yellow
}

# 3. Remove /zeude skill
Write-Host -NoNewline "Removing /zeude skill... "
$SkillFile = Join-Path $ClaudeDir "commands\zeude.md"
if (Test-Path $SkillFile) {
    Remove-Item $SkillFile -Force
    Write-Host "OK" -ForegroundColor Green
} else {
    Write-Host "Not found" -ForegroundColor Yellow
}

# 4. Remove from PATH
Write-Host -NoNewline "Removing PATH configuration... "
$UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($UserPath -like "*\.zeude\bin*") {
    $Parts = $UserPath -split ";" | Where-Object { $_ -notlike "*\.zeude\bin*" -and $_ -ne "" }
    $NewPath = $Parts -join ";"
    [Environment]::SetEnvironmentVariable("PATH", $NewPath, "User")
    Write-Host "OK" -ForegroundColor Green
} else {
    Write-Host "Not found" -ForegroundColor Yellow
}

# 5. Remove .zeude directory
Write-Host -NoNewline "Removing Zeude directory... "
if (Test-Path $ZeudeDir) {
    Remove-Item $ZeudeDir -Recurse -Force
    Write-Host "OK" -ForegroundColor Green
} else {
    Write-Host "Not found" -ForegroundColor Yellow
}

# Summary
Write-Host ""
Write-Host "Uninstall complete!" -ForegroundColor Green
Write-Host "======================================"
Write-Host ""
Write-Host "Zeude has been removed. The original claude command is restored."
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Open a NEW terminal (PATH changes require restart)"
Write-Host "  2. Run 'claude' to use the original Claude CLI" -ForegroundColor Cyan
